name: Daily Fitness Reminder

on:
  schedule:
    # 04:00 UTC entspricht 06:00 Uhr deutscher Zeit
    - cron: '0 4 * * *'
  workflow_dispatch: # Erlaubt es dir, die Mail zum Testen manuell zu triggern

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Reminder Script
        env:
          # Hier wird die Brücke zum GitHub Secret 'MAIL_PW' geschlagen
          MAIL_PW: ${{ secrets.MAIL_PW }} 
        run: python send_reminder.py
